<?php

namespace ContainerR8lkgIm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_86MXt5yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.86MXt5y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.86MXt5y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'editor' => ['privates', '.errored..service_locator.86MXt5y.App\\Entity\\Editor', NULL, 'Cannot autowire service ".service_locator.86MXt5y": it references class "App\\Entity\\Editor" but no such service exists.'],
            'messageGenerator' => ['privates', 'App\\Service\\MessageGenerator', 'getMessageGeneratorService', true],
        ], [
            'editor' => 'App\\Entity\\Editor',
            'messageGenerator' => 'App\\Service\\MessageGenerator',
        ]);
    }
}
