<?php

namespace ContainerR8lkgIm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UIgNl_QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UIgNl.Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UIgNl.Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'gendreRepository' => ['privates', 'App\\Repository\\GendreRepository', 'getGendreRepositoryService', true],
        ], [
            'gendreRepository' => 'App\\Repository\\GendreRepository',
        ]);
    }
}
