<?php

namespace ContainerR8lkgIm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E5J8QOFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e5J8QOF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e5J8QOF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'book' => ['privates', '.errored..service_locator.e5J8QOF.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.e5J8QOF": it references class "App\\Entity\\Book" but no such service exists.'],
            'messageGenerator' => ['privates', 'App\\Service\\MessageGenerator', 'getMessageGeneratorService', true],
        ], [
            'book' => 'App\\Entity\\Book',
            'messageGenerator' => 'App\\Service\\MessageGenerator',
        ]);
    }
}
