<?php

namespace ContainerR8lkgIm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.O6uJzs6.App\Entity\Author' shared service.
     *
     * @return \App\Entity\Author
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.O6uJzs6": it references class "App\\Entity\\Author" but no such service exists.');
    }
}
