<?php

namespace ContainerZgBsVM1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O6uJzs6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O6uJzs6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O6uJzs6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'author' => ['privates', '.errored..service_locator.O6uJzs6.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.O6uJzs6": it references class "App\\Entity\\Author" but no such service exists.'],
            'messageGenerator' => ['privates', 'App\\Service\\MessageGenerator', 'getMessageGeneratorService', true],
        ], [
            'author' => 'App\\Entity\\Author',
            'messageGenerator' => 'App\\Service\\MessageGenerator',
        ]);
    }
}
