<?php

namespace ContainerZgBsVM1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGendreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aQLcU9U.App\Entity\Gendre' shared service.
     *
     * @return \App\Entity\Gendre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.aQLcU9U": it references class "App\\Entity\\Gendre" but no such service exists.');
    }
}
