<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR8lkgIm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR8lkgIm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR8lkgIm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR8lkgIm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR8lkgIm\App_KernelDevDebugContainer([
    'container.build_hash' => 'R8lkgIm',
    'container.build_id' => '59123d0a',
    'container.build_time' => 1616322257,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR8lkgIm');
